### ISSUE TITLE
2.1.7 breaking install with npm

### ISSUE THREAD

**Issue by tovganesh** [ospfranco/link-preview-js#96]
**Describe the bug**
updating to 2.1.7 from 2.1.6 breaks module import using require('link-preview-js');

**To Reproduce**
const linkPreview = require('link-preview-js');
after updating to 2.1.7 from 2.1.6

gives error:
Cannot find module 'link-preview-js'

**Expected behavior**
require('link-preview-js'); 
should work.

**Comment by gnsharma** [comment]
I am also facing this issue. Looks like `2.1.7` deployment is missing `build` directory.

**Comment by ospfranco** [comment]
thanks for reporting! let me take a look asap

**Comment by ospfranco** [comment]
2.1.8 is out, would you mind giving it a try?

**Comment by tovganesh** [comment]
👍 works!
